### ISSUE TITLE
CFAM not a default entity

### ISSUE THREAD

**Issue by gb714us** [andweeb/ki#18]
You should consider adding CFAM as a default entity in v2. I would much appreciate it. Thank you.

**Comment by andweeb** [comment]
Hi @gb714us! It's still in development at the moment but if you'd like a head start you can use the `develop` branch and use a config like this:
```lua
Entity {
    name = "CFAM",
    shortcuts = {
        { nil, nil,
            function()
                if os.date("%A") == "Monday" then
                    Entity.notify("It's :cfam: today", ":dancebear:")
                else
                    Entity.notify("No :cfam: today", ":dogsad:")
                end
            end,
        }
    },
}
```

Not sure if it'll make it into the default config so I'll close this issue, but I'll think about it :)
